plugins {
    id 'java'
    id 'com.diffplug.spotless' version '6.25.0' // Use the latest version
}

group = 'com.common.library'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    implementation 'org.mvel:mvel2:2.5.2.Final'
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

spotless {
    java {
        // Use a standard formatter like Google Java Format
        googleJavaFormat('1.17.0')

        // Optional: Remove unused imports and format import order
        removeUnusedImports()
        importOrder()

        // Optional: Generic text adjustments
        trimTrailingWhitespace()
        endWithNewline()
    }
}
